server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:

  level: INFO
  # Logger-specific levels.
  loggers:
    com.github.nishant141077: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate: ERROR
  appenders:
    - type: console
      threshold: DEBUG                                                         `
      timeZone: IST
      logFormat: "%(%-5level) [%date] [%thread] [%logger{0}]: %message%n"

swagger:
  resourcePackage: com.github.nishant141077.sors.resources
  title: Sors
  description: Personal Wealth Management
  auth:
    users:
      - name: admin
        password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        roles:
          - ADMIN